### ISSUE TITLE
policy provider does not support apply-to

### ISSUE THREAD

**Issue by justindossey** [jjasghar/rabbitmq#135]
From http://www.rabbitmq.com/man/rabbitmqctl.1.man.html : 
```
set_policy [-p vhostpath] [--priority priority] [--apply-to apply-to] {name} {pattern} {definition}
```
so
```
rabbitmqctl set_policy expiry '.*' '{"expires":300000}' --apply-to queues
```
cannot be accomplished with this provider.

**Comment by cmluciano** [comment]
Added in https://github.com/jjasghar/rabbitmq/commit/b6de55453b5b3c275436cda51c631a7d33119164 . I think this can be closed
