### ISSUE TITLE
Configuring default_user and default_pass in rabbitmq.config  is insecure

### ISSUE THREAD

**Issue by wenchma** [jjasghar/rabbitmq#136]
rabbitmq.config template file contains default_user and default_pass which are plain text, it is going to  be a security risk.

{default_user, <<"<%= node['rabbitmq']['default_user'] %>">>},
{default_pass, <<"<%= node['rabbitmq']['default_pass'] %>">>}

In my opinion, we should remove the two configuration items.

**Comment by cmluciano** [comment]
@wenchma Do you still need a fix for this?

**Comment by wenchma** [comment]
@cmluciano yes, I still need a fix, these two attributes should be only stored in rabbitmq db, not exposed in the conf file.

**Comment by cmluciano** [comment]
@wenchma Does #237 work for you?

**Comment by jjasghar** [comment]
@cmluciano and @wenchma seriously it's a clever fix. works for me ;)

**Comment by cmluciano** [comment]
Fix provided by #237 closing now due to inactivity
