### ISSUE TITLE
RabbitMQ Auto-Clustering

### ISSUE THREAD

**Issue by vovans82** [jjasghar/rabbitmq#156]
Hello and thanks for this great cookbook. I only have 1 problem with it. For the first time I have tried using the auto-cluster feature and just like you said in your README to enable cluster I changed:

default['rabbitmq']['cluster'] = true
default['rabbitmq']['cluster_disk_nodes'] = [ 'rabbit@dev-aws-ae1-rabbitmq01', 'rabbit@dev-aws-ae1-rabbitmq02', 'rabbit@dev-aws-ae1-rabbitmq03' ]

All these nodes get a role called rabbitmq which includes: 
  "recipe[rabbitmq_cluster]",
  "recipe[rabbitmq_cluster::plugin_management]"

I just renamed the cookbook because I have another cookbook called rabbitmq. 

I ran chef-client on these nodes many times, stopped and started rabbitmq multiple times manually but the cluster never gets connnected. All nodes act as single nodes. 

[19:48:22][root@dev-aws-ae1-rabbitmq01][/var/log/rabbitmq] # rabbitmqctl cluster_status
Cluster status of node 'rabbit@dev-aws-ae1-rabbitmq01' ...
[{nodes,[{disc,['rabbit@dev-aws-ae1-rabbitmq01']}]},
 {running_nodes,['rabbit@dev-aws-ae1-rabbitmq01']},
 {cluster_name,<<"rabbit@dev-aws-ae1-rabbitmq01">>},
 {partitions,[]}]
[19:54:18][root@dev-aws-ae1-rabbitmq01][/var/log/rabbitmq] #

I get the same status on all the other node except the hostname is different of course. 

And I verified network connectivity between these 3 nodes and I have unrestricted network access and I mean ALL TCP/UDP/ICMP is open between all of these nodes. 

Am I not specifying the default['rabbitmq']['cluster_disk_nodes'] attribute correctly ? 

Thanks

**Comment by cmluciano** [comment]
@vovans82 Currently, clustering is being revamped. Will post back here when the PR is in.

**Comment by jjasghar** [comment]
This should be resolved via #238 if not please reopen.
