### ISSUE TITLE
loopback_users cannot be configured

### ISSUE THREAD

**Issue by nielskrijger** [jjasghar/rabbitmq#159]
Currently I'm using your excellent cookbook to install RabbitMQ. 

We monitor RabbitMQ using Nagios and I want to use RabbitMQ's admin API to do certain checks using a read-only user that can only be used on localhost (similar to the default guest user in RabbitMQ). 

RabbitMQ supports a feature called "loopback_users" that restricts user access to localhost only: https://www.rabbitmq.com/access-control.html

Unfortunately this configuration setting is not available in the cookbook. Is this intentional?

**Comment by sethcall** [comment]
https://github.com/jjasghar/rabbitmq/pull/212

**Comment by jjasghar** [comment]
:+1: awesome, we need a +1 on #212 and a spec and this should be good to merge.

**Comment by cmluciano** [comment]
This can probably be close since #212 is merged
