### ISSUE TITLE
Centos 7.0 support

### ISSUE THREAD

**Issue by jjasghar** [jjasghar/rabbitmq#189]
Welp, it seems we need to work on Centos 7.0 support:

```


           ================================================================================
           Error executing action `install` on resource 'yum_package[erlang]'
           ================================================================================

           Chef::Exceptions::Exec
           ----------------------
            returned 1, expected 0

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/erlang/recipes/package.rb

            46:   package 'erlang'
            47: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/erlang/recipes/package.rb:46:in `from_file'

           yum_package("erlang") do
             action :install
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "erlang"
             version "17.4-1.el6"
             timeout 900
             flush_cache {:before=>false, :after=>false}
             declared_type :package
             cookbook_name "erlang"
             recipe_name "package"
           end

       [2014-12-18T14:04:40-05:00] INFO: Running queued delayed notifications before re-raising exception

       Running handlers:
       [2014-12-18T14:04:40-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2014-12-18T14:04:40-05:00] ERROR: Exception handlers complete
       [2014-12-18T14:04:40-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 4 resources updated in 71.715606627 seconds
       [2014-12-18T14:04:41-05:00] ERROR: yum_package[erlang] (erlang::package line 46) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
       [2014-12-18T14:04:42-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by joerocklin** [comment]
Trying to install erlang on the box manually results in a bunch of yum dependency resolution issues like:
```
Error: Package: erlang-wx-17.4-1.el6.x86_64 (erlang_solutions)
           Requires: libwx_gtk2u_core-2.8.so.0(WXU_2.8)(64bit)
```
no idea on a fix, just hit this issue today. Maybe someone more familiar with the erlang RPMs knows an obvious answer? Full yum output here: https://gist.github.com/joerocklin/89ede769bc5330a3f759

**Comment by stevecstian** [comment]
@jjasghar @joerocklin 
After installing ELEP repo via ```sudo yum install epel-release```, I can install erlang 17.4 on chef/centos-7.0 vagrant box now.  Does that help?

**Comment by joerocklin** [comment]
@stevecstian That does indeed fix the problem. Perhaps the erlang-solutions cookbook needs updating to include EPEL?

**Comment by stevecstian** [comment]
@joerocklin @jjasghar  
In centos 6, `wxBase`/`wxGTK`/`wxGTK-gl` packages could be found in [centos 6 extras repo](http://mirror.centos.org/centos/6/extras/x86_64/Packages/)
```
 wxBase                  x86_64  2.8.12-1.el6.centos    extras            572 k
 wxGTK                   x86_64  2.8.12-1.el6.centos    extras            2.9 M
 wxGTK-gl                x86_64  2.8.12-1.el6.centos    extras             31 k
```
In centos 7, however, `wxBase`/`wxGTK`/`wxGTK-gl` packages are not in [centos 7 extras repo](http://mirror.centos.org/centos/7/extras/x86_64/Packages/) anymore.  Include `yum-epel` recipe should be able to fix the problem, but not sure if this is the best solution.  This issue should be reported to [erlang](https://github.com/opscode-cookbooks/erlang) cookbook... 
```
 wxBase                  x86_64 2.8.12-8.el7             epel             576 k
 wxGTK                   x86_64 2.8.12-8.el7             epel             2.9 M
 wxGTK-gl                x86_64 2.8.12-8.el7             epel              33 k
```

**Comment by jjasghar** [comment]
OK, so it seems we need to spend some time with this. I can't commit to working on this yet; though i'd love to see if the community can pick up some of the slack. 

I'm going to be going into this pretty soon, but not for at least a couple of weeks :sob:

**Comment by stevecstian** [comment]
Thanks @joerocklin for reporting this to opscode-cookbooks/erlang#24. :metal:

**Comment by jjasghar** [comment]
https://github.com/jjasghar/rabbitmq/pull/214 resolves this.

**Comment by cmluciano** [comment]
This can probably be closed since #214 is merged

**Comment by liaogx** [comment]
Has this problem been resolved? I encountered the same problem when installing erlang

**Comment by isuftin** [comment]
We are running this on CentOS 7 currently. Seems to be working?
