### ISSUE TITLE
Wrong service provider used on Linux Mint

### ISSUE THREAD

**Issue by rlipscombe** [jjasghar/rabbitmq#194]
When using the 'rabbitmq' (https://supermarket.chef.io/cookbooks/rabbitmq) cookbook, chef-solo (v11.16.4) fails with:

    Error executing action `enable` on resource 'service[rabbitmq-server]'
    File '/etc/init/rabbitmq-server.conf' does not exist

This is because chef assumes that Linux Mint uses upstart; for the rabbitmq package, it's still using init.d.

So the `action [:enable]` attribute does the wrong thing.

(Originally reported as https://github.com/opscode/chef/issues/2726)

**Comment by jjasghar** [comment]
Ah, thanks for this. We don't test against Linux Mint.  If you would like to put a PR in to have the support please do, but i'm planning on just focusing on what we support in [kitchen.cloud.yml](https://github.com/jjasghar/rabbitmq/blob/master/.kitchen.cloud.yml).

**Comment by rlipscombe** [comment]
I'd love to, but I'm unsure about the best way to fix this. At the moment, I've just put the following earlier in the run list:

```
if platform?("linuxmint")
    service node['rabbitmq']['service_name'] do
        provider Chef::Provider::Service::Debian
    end
end
```

...which feels kinda dirty.
