### ISSUE TITLE
New version 3.4.3 released

### ISSUE THREAD

**Issue by jjasghar** [jjasghar/rabbitmq#195]
Check out @RabbitMQ's Tweet: https://twitter.com/RabbitMQ/status/552798282129608704?s=09

I'll start the PR asap.

**Comment by stevecstian** [comment]
@jjasghar typo in PR subject :wink:

**Comment by jjasghar** [comment]
Got the PR written, testing it and I'll push today

**Comment by stevecstian** [comment]
Oops, I meant there is a typo in the subject of this issue...

**Comment by jjasghar** [comment]
https://github.com/jjasghar/rabbitmq/pull/196
