### ISSUE TITLE
Chef restarts RabbitMQ because it always set the permissions to all the users when it runs

### ISSUE THREAD

**Issue by demonccc** [jjasghar/rabbitmq#197]
Hi,

I was checking the code and I found that the cookbook use this command to detect user the policies:
```
cmd = "rabbitmqctl -q list_user_permissions #{name} | grep \"^#{vhost}\\b\""
```
When vhost is /, the grep command doesn't match and the function `user_has_permissions?` returns **false** (*permissions found but do not match*).

I tested the command manually:
```
#  rabbitmqctl -q list_user_permissions bell-rw
/       bell|q-.+@.+    bell|q-.+@.+    bell|q-.+@.+
# rabbitmqctl -q list_user_permissions bell-rw | grep "/\b"
```
And I tested the command grep by using the command echo to emulate the rabbitmqctl output:
```
# echo "/       bell|q-.+@.+    bell|q-.+@.+    bell|q-.+@.+"  | grep "/\b"
# echo "/lala       bell|q-.+@.+    bell|q-.+@.+    bell|q-.+@.+"  | grep "/lala\b"
/lala       bell|q-.+@.+    bell|q-.+@.+    bell|q-.+@.+
```

Regards.

**Comment by cmluciano** [comment]
Is this still a problem for you?

**Comment by johnbellone** [comment]
Ah I think I am hitting this also.

**Comment by demonccc** [comment]
Hi, I didn't see any change in the code... Have you changed anything? I didn't test the new version of this cookbook.

**Comment by scalp42** [comment]
@cmluciano @jjasghar any plans for this ?

**Comment by jjasghar** [comment]
@scalp42 i'll be honest, i havent dug into this at all.

If you have a fix, i'd love to see it, but i'll put it on my TODO and ideally get to it soon.

**Comment by scalp42** [comment]
@jjasghar okay I'll try to get to it early next week unless @demonccc has a fix for it already

**Comment by jjasghar** [comment]
@scalp42 awesome to hear. thanks! :metal:

**Comment by scalp42** [comment]
@demonccc @jjasghar this was fixed in https://github.com/jjasghar/rabbitmq/commit/a1bb98be433d62b181dc420577e0322b08394113 

Can be closed :smile:

**Comment by demonccc** [comment]
Thanks!
