### ISSUE TITLE
erlang broken

### ISSUE THREAD

**Issue by zeroXten** [jjasghar/rabbitmq#199]
Can't use a recent version of erlang on RHEL because of the hardcoded compat rpm. Can't say I understand why that is needed, but it should either be removed or at least turned into an attribute.

**Comment by stevecstian** [comment]
See #106

**Comment by jjasghar** [comment]
@zeroXten as @stevecstian says there is a PR that fixes this, but it's out of date. We need someone to :+1: it and also probably rebase.

**Comment by cmluciano** [comment]
#220 should fix this
