### ISSUE TITLE
Can't successfully rerun the cookbook if set the wrong parameter the first time

### ISSUE THREAD

**Issue by lanqisong** [jjasghar/rabbitmq#201]
If the first time I set the wrong parameter e.g node['rabbitmq']['address'] ,  the cookbook exited when restarting the rabbitmq.
Then second time I corrected the node['rabbitmq']['address'], and rerun the recipe, it will exited before the reconfigure the rabbitmq-env.conf file.  Because the recipe will try to start the rabbtimq before reconfigure at this line:   https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L115-L117

**Comment by jjasghar** [comment]
It looks like we repeat that line per the case statement. It'll probably be a good idea to pull it out and put it at the bottom of the recipe. 

I'll put together a PR today of what i'm suggesting, and maybe you could test it?

**Comment by jjasghar** [comment]
https://github.com/jjasghar/rabbitmq/pull/202, @lanqisong can you test please?

**Comment by lanqisong** [comment]
@jjasghar I have tested the patch, look good to me, I think you could merge it to the master branch, thanks!
