### ISSUE TITLE
Add Gemfile.lock to Repository

### ISSUE THREAD

**Issue by tsupertramp** [jjasghar/rabbitmq#209]
As i have problems with some gem dependencies which did not occur yesterday i would like to ask, why there is no Gemfile.lock in the repository?
This would help to keep track of the specific gem versions and would allow us
to develop with the 'right' gem versions.

Greeting @it_supertramp

**Comment by michaelklishin** [comment]
This is a reasonable request.

**Comment by stevecstian** [comment]
Paging @jjasghar

**Comment by jjasghar** [comment]
I'm torn on the whole Gemfile.lock honestly. I came up learning ruby when the Gemfile.lock was considered a fopaux. 

It's mainly for development work though? I mean you probably already have chef installed and arent using the gem, we need to bind to a specific version of foodcritic? not really, chefspec nah...

I dunno, what can we gain with it? If it's dependency management, do you use gemsets for development work?

I'm looking for input here i guess.

**Comment by tsupertramp** [comment]
From my point of view it is important to add it.

I want to a give an example:
- User A pushes into master - build is green. (some gem has version 3.0.1)
- User B pushes the same code into master (a hour later) - build is red (the gem has version 3.0.2 released)

Last weekend i wanted to rebuild my merge request with your annotations but i got stuck in some
weird problem. Now i know it was some gem which made problem.

Our mission should be to have an idempotent build - If we build a second time, we should get
the same result as the first build. Regardless which date (which gems are released) is today.

If we would add the Gemfile.lock we would gain the ability to have a strict definition and every contributor could be sure that his state (passing tests) will work tomorrow as well.

Greetings Thomas

**Comment by jjasghar** [comment]
Good enough for me, i put this in: https://github.com/jjasghar/rabbitmq/pull/213 is this what you're expecting?

Yes I did test it too before pushing it up :wink:

**Comment by tsupertramp** [comment]
Yeah :+1: - Thank you! I'll spend a beer on chefconf!
