### ISSUE TITLE
version pining does not work by default with use_distro_version

### ISSUE THREAD

**Issue by kramvan1** [jjasghar/rabbitmq#210]
There are two attributes used when trying to install the rabbitmq package from the default disto repo:
use_distro_version which defaults to False, and version which defaults to 3.4.3.

if node['rabbitmq']['use_distro_version']
    package 'rabbitmq-server' do
      action :install
      version node['rabbitmq']['version']
    end

When setting the use_distro_version to true, it will most likely always fail since the version 3.4.3 is not usually available in the distro repo's yet.    So, that means to have to specific the version attribute and are forced into pinning down your distro version.   I think that's the opposite of what most folks want here when using the default distro version. 

I would like to propose two choices here

A. Simple remove the version attribute from the distro package install resource.  That would line up better with how most other cookbook are done.

B. Add another flag to make the pinning of the distro version optional, like:
if node['rabbitmq']['use_distro_version']
    package 'rabbitmq-server' do
      action :install
      version node['rabbitmq']['version'] if node['rabbitmq']['pin_distro_version']
    end

Opinions on which approach to take here?

**Comment by smurawski** [comment]
@jjasghar Any thoughts?  @kramvan1 came in to office hours and I liked option 2.  He's going to create a PR on that.

**Comment by kramvan1** [comment]
https://github.com/jjasghar/rabbitmq/pull/211    Created this PR for option B.
