### ISSUE TITLE
Use default version not working in CentOS

### ISSUE THREAD

**Issue by cmluciano** [jjasghar/rabbitmq#218]
While yum-epel has packages for centos 6.5, 6.6, and 7.0- these packages are out of date and therefore will not likely align with the default 3.4.3. I think that the only way that it would, is if someone is replicating these to their own personal server. As such the "default-use-distro-version" test suite will always fail with our default values. 

I have come up with a few solutions that I can submit a PR for.
1. Edit the test-suite "default-use-distro-version" with versions that we know are available in YUM epel. (probably the easiest and most clean)
2. Create a new test-suite in mini-test fashion and import a repo that might have up to date versions.
3. Deprecate this feature in CentOS since the packages from yum-epel are several x.Y.z behind.

**Comment by jjasghar** [comment]
Great points. I'm leaning towards to 1 out of these; it seems like the best option.

**Comment by cmluciano** [comment]
Closed via #223
