### ISSUE TITLE
Installation fails if you decide to install erlang from sources

### ISSUE THREAD

**Issue by ecorderob** [jjasghar/rabbitmq#224]
Hi,

When I try to install the default erlang packages in my AWS instance (prior to install rabbitmq), the release that is downloaded is 14.04, which is quite old.  To be able to work with the latest one, I need to install erlang from sources  passing a couple of parameters to the cookbook

default['erlang']['install_method'] = 'source'
default['erlang']['source']['version'] =  '17.4'
default['erlang']['source']['url'] = 'url'
default['erlang']['source']['checksum'] = 'xxxxx'

The problem that I face is that when rabbitmq tries to install itself (from RPM) it fails to do it because of the erlang dependencies (does not find the erlang rpm installed).

It would be nice if you could include an option to pass "--nopeds" to the RPM rabbitmq installation so that it would not fail at this point.

**Comment by cmluciano** [comment]
I think this is maybe a problem more with the upstream cookbook for erlang. It looks to be hardcoded (as you said with) [R15B01](https://github.com/opscode-cookbooks/erlang/blob/master/attributes/default.rb#L21). I'm wondering if that cookbook attribute should just be bumped. 

Another option is to add an attribute to our cookbook that overrides whatever Erlang version that you want to install. @jjasghar What do you think?

Would activating the ESL attribute do the trick?

**Comment by jjasghar** [comment]
So I merged this https://github.com/jjasghar/rabbitmq/pull/214/files and if you see it does that ESL trick right? But that's for CentOS 7 specifically. 

I haven't tested this on AWS, is it specific to an amazon release? Offically we don't have AWS as part of the kitchen.yml.

**Comment by cmluciano** [comment]
That's true, AFAIK AWS uses a RHEL derivative so the repos might be different, yet it should still be able to pull from the "erlang solutions" repo. 

@ecorderob Can you give more background on the OS and version that you are using? Potentially ```cat /etc/redhat_release```

**Comment by ecorderob** [comment]
Hi @cmluciano I am using the latest Amazon Linux 2014.09.  No /etc/redhat_release in that OS.

**Comment by jjasghar** [comment]
Ah so we've pulled support for Amazon Linux. Right now we only support what we have in the [.kitchen.cloud.yml](https://github.com/jjasghar/rabbitmq/blob/master/.kitchen.cloud.yml) or the [.kitchen.yml](https://github.com/jjasghar/rabbitmq/blob/master/.kitchen.yml). If you would like support for Amazon Linux I'm all ears but i'll need you to spear head and take ownership of it.

**Comment by cmluciano** [comment]
@ecorderob I added a commit to the upstream erlang cookbook to always include yum-epel and yum-erlang-solutions to RHEL based OSes. Watch for the latest release of the erlang cookbook and see if that works for you. I will try to bring this up in the Chef Office Hours today.

**Comment by cmluciano** [comment]
My PR has been merged https://github.com/opscode-cookbooks/erlang/pull/25
