### ISSUE TITLE
Add support for multiple nodes on one machine

### ISSUE THREAD

**Issue by andre1810** [jjasghar/rabbitmq#225]
Hello,
I need support for running multiple nodes on one machine because of high availability. This nodes will be clustered..

Best regards
André

**Comment by michaelklishin** [comment]
It would make the cookbook significantly more complicated. And multiple nodes on a single machine is hardly a high degree HA: your machine may lose power.

**Comment by cmluciano** [comment]
Dup of #125

**Comment by jjasghar** [comment]
Closing due to Dup of #125
