### ISSUE TITLE
Type Error with newest code

### ISSUE THREAD

**Issue by bphinney** [jjasghar/rabbitmq#227]
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/rabbitmq/libraries/default.rb
================================================================================

TypeError
---------
Chef is not a module

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/rabbitmq/libraries/default.rb:19:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/rabbitmq/libraries/default.rb:

 12:  # Unless required by applicable law or agreed to in writing, software
 13:  # distributed under the License is distributed on an "AS IS" BASIS,
 14:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 15:  # See the License for the specific language governing permissions and
 16:  # limitations under the License.
 17:  #
 18:  
 19>> module Chef Software
 20:    # module rabbit
 21:    module RabbitMQ
 22:      # This method does some of the yuckiness of formatting parameters properly
 23:      # for rendering into the rabbit.config template.
 24:      def format_kernel_parameters  # rubocop:disable all
 25:        rendered = []   # rubocop:enable all
 26:        kernel = node['rabbitmq']['kernel'].dup
 27:  
 28:        # This parameter is special and needs commas instead of periods.

**Comment by cmluciano** [comment]
I think this is related to this [commit](https://github.com/jjasghar/rabbitmq/commit/1823240b07d70bff226dc5087f6109a566d35864). I believe that my [PR#226](https://github.com/jjasghar/rabbitmq/pull/226) should fix this.

**Comment by bphinney** [comment]
On 02/18/2015 11:09 AM, Chris L wrote:
>
> I think this is related to this commit 
> <https://github.com/jjasghar/rabbitmq/commit/1823240b07d70bff226dc5087f6109a566d35864>. 
> I believe that my PR#226 
> <https://github.com/jjasghar/rabbitmq/pull/226> should fix this.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jjasghar/rabbitmq/issues/227#issuecomment-74891341>.
>

I agree.

**Comment by cmluciano** [comment]
I take that back, I think there is a nameclash. Opcode is probably not what we want to call it, but I think I should just revert to back to Opscode for now so that the module can be properly included.

**Comment by cmluciano** [comment]
Updated [PR](https://github.com/jjasghar/rabbitmq/pull/228)

**Comment by cmluciano** [comment]
@bphinney try the updated code now

**Comment by bphinney** [comment]
@cmluciano - Yes it is working for me now, thanks.
