### ISSUE TITLE
Recipe stops server to change erlang cookie even when it's not necessary

### ISSUE THREAD

**Issue by dblessing** [jjasghar/rabbitmq#232]
I am having a strange issue that I can't explain. Every time I run Chef it's stopping the rabbit server to  change the erlang cookie. It logs 'stop to change erlang cookie' and then the template says 'up to date' so the server never gets restarted. I have invoked chef-shell and read in the erlang file and compared it to the node attribute and everything is good. I can't figure out why during runtime it's complaining. Any ideas? This is using rabbit cookbook version 3.8.0. I cannot see that anything in 3.10.0 would help this issue.

**Comment by dblessing** [comment]
I'm an idiot. Thanks for your time lol.

**Comment by jjasghar** [comment]
What was the resolution? Should we document it so others don't fall in the trap?

**Comment by dblessing** [comment]
@jjasghar I was including the recipe and *then* setting the attribute. Set attribute first :stuck_out_tongue:

**Comment by jjasghar** [comment]
Ha! Yeah been there done that, glad you caught it and got it resolved :metal:
