### ISSUE TITLE
seems cookbook is unable to set/override default username & password #245

### ISSUE THREAD

**Issue by nlawson** [jjasghar/rabbitmq#246]
see issue #245 for details

**Comment by nlawson** [comment]
https://github.com/jjasghar/rabbitmq/issues/245

**Comment by cmluciano** [comment]
Are you using a wrapper cookbook or manually editing the the node?

**Comment by nlawson** [comment]
I'm running on AWS, using hosted chef, for the test i manually deleted the mnesia folder.

**Comment by cmluciano** [comment]
So I'm guessing to override you are running ```knife node edit node``` and then changing the json?

**Comment by nlawson** [comment]
I'm setting the attributes in the environment, using knife environment edit ...
then changing the son

**Comment by jjasghar** [comment]
Please comment in #245, i'm closing this one and reopening #245.
