### ISSUE TITLE
Error for clustering cluster_nodes use with cluster.rb

### ISSUE THREAD

**Issue by rlanore** [jjasghar/rabbitmq#265]
into readme it's write:

> node['rabbitmq']['clustering']['cluster_nodes'] = [ { :name => 'rabbit@rabbit1', :type => 'disc' },

name attributes is only with single quote. 

On my debian 7 and rabbitmq-server 3.5.1-1 the result of

> rabbitmqctl eval "node()."

is 

> 'rabbit@silog-front3'

so into  cluster.rb:230

> var_cluster_node_type = parse_cluster_nodes_string(new_resource.cluster_nodes).select { |node| node['name'] == var_node_name }.first['type']

I have an
> undefined method `[]' for nil:NilClass

If i write my attribute with :

> node.default['rabbitmq']['clustering']['cluster_nodes'] = [{:name => "'rabbit@silog-front3'",:type => "disc"}]

It's work

**Comment by monkey1016** [comment]
Looks like there are some cases where `rabbitmqctl eval "node()."` returns a name with single-quotes and some other instances where it returns a name without single-quotes.  I think it has to do with dashes in the short hostname:
```bash
[vagrant@rabbitmq1 ~]$ sudo rabbitmqctl eval "node()."
rabbit@rabbitmq1
```
vs
```bash
[vagrant@rabbitmq-1 ~]$ sudo rabbitmqctl eval "node()."
'rabbit@rabbitmq-1'
```

**Comment by jperville** [comment]
+1, thanks for fixing the issue @monkey1016
