### ISSUE TITLE
Feature Request: Support rabbitmq_user with multiple vhosts.

### ISSUE THREAD

**Issue by jemc** [jjasghar/rabbitmq#278]
RabbitMQ has the ability to give a single user access to more than one vhost.  It would be nice to be able to take advantage of this from a recipe.

in our case, it is for a master admin user that has admin access to all vhosts, such as:
```ruby
# Create a user for administration of all vhosts
rabbitmq_user "overall_admin" do
  vhost ["/", "foo", "bar"]
  password overall_admin_password
  permissions ".* .* .*"
  tag "administrator"
  action [:add, :set_permissions, :set_tags]
end
```

**Comment by michaelklishin** [comment]
:+1:
