### ISSUE TITLE
Logrotate Error on Ubuntu 14.04

### ISSUE THREAD

**Issue by rudijs** [jjasghar/rabbitmq#283]
Hi,

I'm using this cookbook to install RabbitMQ on Ubuntu 14.04

I'm getting this error emailed to my from the server:

```
/etc/cron.daily/logrotate:
logrotate_script: 2: logrotate_script: /etc/init.d/rabbitmq-server: not found
error: error running shared postrotate script for '/var/log/rabbitmq/*.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

The logrotate configuration at etc/logrotate.d/rabbitmq-server is:

```
/var/log/rabbitmq/*.log {
        weekly
        missingok
        rotate 20
        compress
        delaycompress
        notifempty
        sharedscripts
        postrotate
            /etc/init.d/rabbitmq-server rotate-logs > /dev/null
        endscript
}
```

There is no file /etc/init.d/rabbitmq-server which is causing the error.

I think the postrotate command should be: `rabbitmqctl rotate_logs`

Looks like it's related to the package install rather than this cookbook I think?

If so, should I make a simple custom rabbitmq logrotate recipe or is there something in the current cookbook I can use?

Thanks!

**Comment by jjasghar** [comment]
I'm not sure to be honest. It seems we still use Upstart. https://github.com/jjasghar/rabbitmq/blob/master/recipes/default.rb#L74-L84. We need to get this fixed :crying_cat_face:

**Comment by jjasghar** [comment]
Is this still an issue?

**Comment by rudijs** [comment]
@jjasghar Hi, I'm not sure to be honest.

My workflow has changed, I use the docker coobook to manage my rabbitmq instances.

I guess we can close it and re-open if someone else has issues.

**Comment by markunsworth** [comment]
Yes still an issue - when removing the init.d script we should also be changing the logrotate conf for rabbitmq-server as the one installed by the deb package points to the init.d script to call a rotate_logs command. 

I've just submitted a pull request #341 which should resolve this
