### ISSUE TITLE
Server failing unable to restart, able to restart when resetting queues

### ISSUE THREAD

**Issue by Black-Star** [jjasghar/rabbitmq#289]
Here is thee error

      {"init terminating in do_boot",{rabbit,failure_during_boot,{could_not_start,rabbit,{bad_return,{{rabbit,start,[normal,[]]},{'EXIT',{rabbit,failure_during_boot,{badmatch,{error,{{{function_clause,[{rabbit_queue_index,journal_minus_segment1,[{no_pub,del,no_ack},{{<<16 bytes>>,{message_properties,undefined,false},true},del,ack}],[{file,"src/rabbit_queue_index.erl"},{line,989}]},{rabbit_queue_index,'-journal_minus_segment/2-fun-0-',4,[{file,"src/rabbit_queue_index.erl"},{line,973}]},{array,sparse_foldl_3,7,[{file,"array.erl"},{line,1675}]},{array,sparse_foldl_2,9,[{file,"array.erl"},{line,1669}]},{rabbit_queue_index,'-recover_journal/1-fun-0-',1,[{file,"src/rabbit_queue_index.erl"},{line,701}]},{lists,map,2,[{file,"lists.erl"},{line,1224}]},{rabbit_queue_index,segment_map,2,[{file,"src/rabbit_queue_index.erl"},{line,819}]},{rabbit_queue_index,recover_journal,1,[{file,"src/rabbit_queue_index.erl"},{line,693}]}]},{gen_server2,call,[<0.200.0>,out,infinity]}},{child,undefined,msg_store_persistent,{rabbit_msg_store,start_link,[msg_store_persistent,"/var/lib/rabbitmq/mnesia/rabbit@ip-10-63-162-69",[],{#Fun<rabbit_queue_index.2.132977059>,{start,[{resource,<<1 byte>>,queue,<<6 bytes>>}]}}]},transient,4294967295,worker,[rabbit_msg_store]}}}}}}}}}}}

**Comment by jjasghar** [comment]
Can you define "resetting" queues?

**Comment by jjasghar** [comment]
@michaelklishin maybe you can help out here?

**Comment by michaelklishin** [comment]
RabbitMQ couldn't recover its queue index. Resetting a node removes the entire internal database.

**Comment by jjasghar** [comment]
Ah cool, than that's not a cookbook issue. We don't create queues either with the cookbook, we just set up rabbitmq so this is out of scope.
