### ISSUE TITLE
Upgrade to "-3_all.deb"

### ISSUE THREAD

**Issue by jdrago999** [jjasghar/rabbitmq#311]
Hi -

This page - https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.5/ - no longer lists 3.5.5-1_all.deb, but the cookbook was still referring to it.

I've submitted a PR to address this.

**Comment by michaelklishin** [comment]
Packages still have revision 1 by default. `3.5.5` is an exception because we had to rebuild packages. I'd recommend upgrading to `3.5.6` rather than bumping package revision to `3` by default. It would break more things than it fixes, I think.

@jjasghar

**Comment by jjasghar** [comment]
Mind putting together a PR on what you think should happen? I'm cool with whatever you think is right; i want to be instep with upstream.

**Comment by michaelklishin** [comment]
@jjasghar #310 needs to be reverted, default version bumped to `3.5.6`, that is all.

**Comment by michaelklishin** [comment]
Sorry, #310 is an issue, I was referring to this PR.

**Comment by michaelklishin** [comment]
Submitted #313, #314.

**Comment by martinb3** [comment]
I was going to suggest switching to PackageCloud RE: #304, but its packages are about 2 months behind as well :(
