### ISSUE TITLE
Problems getting erlang 1.5.x version on Ubuntu 14.04

### ISSUE THREAD

**Issue by gprakashmosaixsoft** [jjasghar/rabbitmq#336]
When I install this cookbook with

knife cookbook site install rabbitmq -o ./cookbooks

and then try to run
chef-client -z -o rabbitmq

I get 

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
Could not satisfy version constraints for: erlang

I don't know why even though your metadata file says ~>1.5.0, knife installs erlang version 2.0.1 (the latest). Does anyone know what I can do to get around this?

Thanks

Gagan Prakash

**Comment by jjasghar** [comment]
I'd suggest pulling down the older version of erlang cookbook and uploading it to your chef server. I haven't updated this cookbook for the newer version of erlang yet, but I'm due for a refresh on this cookbook very soon.

**Comment by jjasghar** [comment]
Please give that a try, I'm going to close this, but reopen if you still have issues.

**Comment by gprakashmosaixsoft** [comment]
So I asked in the chef irc and it seems the issue is related to knife not being a very good dependency manager so I switched to Bershelf and that seems to allow me to restrict the erlang version to 1.5.8 so things work.
