### ISSUE TITLE
RabbitMQ 3.6.2 will have a dependency on socat

### ISSUE THREAD

**Issue by michaelklishin** [jjasghar/rabbitmq#355]
This is a heads-up, not an issue: in RabbitMQ 3.6.2, packages will depend on `socat` but [apparently with some installation methods that dependency is ignored](https://groups.google.com/forum/#!topic/rabbitmq-users/HiKSUkaPZtM).

It would be very nice if this project installed the `socat` package before installing RabbitMQ.

**Comment by jjasghar** [comment]
Ah nice thanks @michaelklishin.  Is the `socat` package just a standard pkg from `apt` or `yum`?

**Comment by michaelklishin** [comment]
On Ubuntu it is [provided starting with 12.04](http://packages.ubuntu.com/search?keywords=socat&searchon=names&suite=all&section=all).

`socat` is also available for [Debian Jessie](https://packages.debian.org/jessie/socat) and later versions.

I could only find so much about yum: according to [Percona installation docs](https://www.percona.com/doc/percona-xtradb-cluster/5.6/installation/yum_repo.html), `socat` has to be installed [from EPEL](https://fedoraproject.org/wiki/EPEL).

**Comment by binarin** [comment]
It's in EPEL for CentOS 6, and directly available in CentOS 7. Probably the same holds for RHEL.

**Comment by jjasghar** [comment]
Awesome, I'll get the PR together and ask yall both to verify. :metal:

**Comment by jjasghar** [comment]
https://github.com/jjasghar/rabbitmq/pull/372 should be what we need right?

**Comment by michaelklishin** [comment]
@jjasghar 👍

**Comment by bericoberin** [comment]
Is there any way to make socat optional?  Or at the very least ensure that the RPM requires version 1.7.3.1 or newer?  see: https://www.pcworld.com/article/3029389/socat-vulnerability-shows-that-crypto-backdoors-can-be-hard-to-spot.html

I can't use RabbitMQ if I have to use a library with a known security hole.

**Comment by michaelklishin** [comment]
@bericoberin you can use any `socat` version. This is not the right place to discuss RPM package dependencies: this is a Chef cookbook.
