### ISSUE TITLE
what i should do about rabbitmq lay4 check？

### ISSUE THREAD

**Issue by Michael754267513** [jjasghar/rabbitmq#386]
this is a example about check redis.
       option tcp-check
        tcp-check send PING\r\n
        tcp-check expect string +PONG
        tcp-check send QUIT\r\n
        tcp-check expect string +OK
[root@QA-PUB01 conf]# telnet 192.168.2.216 6379
Trying 192.168.2.216...
Connected to 192.168.2.216.
Escape character is '^]'.
ping
+PONG
quit
+OK
Connection closed by foreign host.
when i post a command,redis give me a string.but rabbitmq i not found this feature!
how to config about rabbitmq？

**Comment by jjasghar** [comment]
This seems like the wrong place to ask this question, please ask proper RabbitMQ repos? https://github.com/rabbitmq

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users.

**Comment by Michael754267513** [comment]
Sorry
